version: "3.3"
services:
  frontend:
    build: .    
    ports:
      - "80:80"
      - "443:443"
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
