version: "3.3"
services:
  frontend:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/etc/ssl/
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
