apiVersion: v1
kind: Service
metadata:
  name: tumbler-service
  labels:
    app: tumbler
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: tumbler
    tier: frontend
  ports:
    - name: vanilla
      protocol: TCP
      port: 80
      targetPort: 80
    - name: tls
      protocol: TCP
      port: 443
      targetPort: 443
  