name: test-action
on: [push]
jobs:
  ssh-remote-cmds:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/scribble/myremotesubdir/tumbler
            git checkout ${{ steps.extract_branch.outputs.branch }}
            git pull
            kubectl delete -f service.yaml
            kubectl delete -f backend-service.yaml
            kubectl delete -f deployment.yaml
            kubectl delete -f backend-deployment.yaml
            docker-compose build
            kind load docker-image tumbler_backend:latest
            kind load docker-image tumbler_frontend:latest
            kubectl apply -f backend-deployment.yaml
            kubectl apply -f deployment.yaml
            kubectl apply -f backend-service.yaml
            kubectl apply -f service.yaml
